parameters:
#    the_click_cms_upload.example.class: TheClickCms\UploadBundle\Example

services:
#    the_click_cms_upload.example:
#        class: %the_click_cms_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
